<a href="https://colab.research.google.com/github/Prakritish-bhattacharya/NamasteAI/blob/NamsateAI-Practical-Learning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** is the foundational open-source library for *scientific computing and data analysis* in Python

# What NumPy Does
* Adds support for large, multi-dimensional arrays and matrices to Python.
* Provides high-performance mathematical, logical, and statistical routines.
* Serves as the core engine for higher-level data tools like pandas, scikit-learn, and TensorFlow

# Why NumPy is Important
* **Speed:**
 Operations run in pre-compiled C code instead of slow, sequential Python loops.
* **Memory Efficiency:** Data is stored in contiguous blocks of memory with uniform types, reducing overhead.
* **Vectorization & Broadcasting:** Enables math operations on entire arrays at once without writing explicit loops.

In [1]:
# import numpy library
import numpy as np

**Basic Array Creation**

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr = np.array([1,2,3,"Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
np.array(arr)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Array Generation function**

`np.arange()`: Generates evenly spaced values within a given interval based on a step size. It works similarly to Python's native `range()`.

In [17]:
arr_arange = np.arange(0,10)
print(arr_arange)
# ----------------------------------------
arr2_arange = np.arange(0,10,2)
print(arr2_arange)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


`np.zeros()`: Creates an array of a specified shape filled entirely with **zeros** (default type is float).

In [21]:
arr_zero = np.zeros((2,3))# ((#2 rows, #3 columns))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])