<a href="https://colab.research.google.com/github/Prakritish-bhattacharya/NamasteAI/blob/NamsateAI-Practical-Learning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** is the foundational open-source library for *scientific computing and data analysis* in Python

# What NumPy Does
* Adds support for large, multi-dimensional arrays and matrices to Python.
* Provides high-performance mathematical, logical, and statistical routines.
* Serves as the core engine for higher-level data tools like pandas, scikit-learn, and TensorFlow

# Why NumPy is Important
* **Speed:**
 Operations run in pre-compiled C code instead of slow, sequential Python loops.
* **Memory Efficiency:** Data is stored in contiguous blocks of memory with uniform types, reducing overhead.
* **Vectorization & Broadcasting:** Enables math operations on entire arrays at once without writing explicit loops.

In [1]:
# import numpy library
import numpy as np

**Basic Array Creation**

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr = np.array([1,2,3,"Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
np.array(arr)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Array Generation function**

`np.arange()`: Generates evenly spaced values within a given interval based on a step size. It works similarly to Python's native `range()`.

In [17]:
# np.arange(start, stop, step)
arr_arange = np.arange(0,10)
print(arr_arange)
# ----------------------------------------
arr2_arange = np.arange(0,10,2)
print(arr2_arange)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


`np.zeros()`: Creates an array of a specified shape filled entirely with **zeros** (default type is float).

In [21]:
arr_zero = np.zeros((2,3))# ((#2 rows, #3 columns))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

`np.ones()`: Creates an array filled entirely with **ones**.

In [23]:
arr_ones = np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

`np.linspace()`: Generates an array of evenly spaced numbers over a specified range, but you define the **total number of samples** instead of the step size.

In [31]:
# np.linspace(start, stop, number_of_elements)
arr_linspace = np.linspace(0,10,5)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.random.rand(10)

array([0.91895819, 0.91603103, 0.52190653, 0.80789216, 0.20605724,
       0.39955318, 0.53180961, 0.47627716, 0.58981444, 0.91158393])

In [38]:
np.random.randn(10)

array([ 0.12515219, -0.76140761, -0.11360098, -0.57164824, -1.23838215,
        0.35129122,  2.13577207, -0.23585709,  0.91422444,  0.18399772])

In [45]:
# (start, end, numbers_of_elements)
np.random.randint(0,10,10)

array([7, 9, 8, 6, 0, 9, 3, 3, 1, 6])

# Array Attributes

In NumPy, **array attributes** are built-in properties of the `ndarray` object that provide critical details about its structure, data type, and memory layout. You can access these properties directly using dot notation (e.g., `array.shape`) without calling
them like functions.


---


## NumPy Array Attributes

| Attribute | What it Returns | Example Output (for a 2×3 array) |
|---|---|---|
| `.shape` | A tuple showing the size of the array in each dimension (rows, columns). | `(2, 3)` |
| `.ndim` | The number of array dimensions (axes). | `2` |
| `.dtype` | The data type of the elements stored in the array. | `dtype('int64')` |
| `.size` | The total number of elements across all dimensions. | `6` |
| `.itemsize` | The size of a single array element in bytes. | `8` (for a 64-bit integer) |
| `.nbytes` | The total memory consumed by all elements (`size × itemsize`). | `48` (6 elements × 8 bytes) |