<a href="https://colab.research.google.com/github/Prakritish-bhattacharya/NamasteAI/blob/NamsateAI-Practical-Learning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy** is the foundational open-source library for *scientific computing and data analysis* in Python

# What NumPy Does
* Adds support for large, multi-dimensional arrays and matrices to Python.
* Provides high-performance mathematical, logical, and statistical routines.
* Serves as the core engine for higher-level data tools like pandas, scikit-learn, and TensorFlow

# Why NumPy is Important
* **Speed:**
 Operations run in pre-compiled C code instead of slow, sequential Python loops.
* **Memory Efficiency:** Data is stored in contiguous blocks of memory with uniform types, reducing overhead.
* **Vectorization & Broadcasting:** Enables math operations on entire arrays at once without writing explicit loops.

In [4]:
# import numpy library
import numpy as np

**Basic Array Creation**

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr = np.array([1,2,3,"Hello"])
arr

array(['1', '2', '3', 'Hello'], dtype='<U21')

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
np.array(arr)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Array Generation function**

`np.arange()`: Generates evenly spaced values within a given interval based on a step size. It works similarly to Python's native `range()`.

In [8]:
# np.arange(start, stop, step)
arr_arange = np.arange(0,10)
print(arr_arange)
# ----------------------------------------
arr2_arange = np.arange(0,10,2)
print(arr2_arange)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


`np.zeros()`: Creates an array of a specified shape filled entirely with **zeros** (default type is float).

In [9]:
arr_zero = np.zeros((2,3))# ((#2 rows, #3 columns))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

`np.ones()`: Creates an array filled entirely with **ones**.

In [10]:
arr_ones = np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

`np.linspace()`: Generates an array of evenly spaced numbers over a specified range, but you define the **total number of samples** instead of the step size.

In [11]:
# np.linspace(start, stop, number_of_elements)
arr_linspace = np.linspace(0,10,5)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.random.rand(10)

array([0.44381721, 0.86494878, 0.33548431, 0.16092168, 0.04082277,
       0.7481114 , 0.6524803 , 0.39184074, 0.31157758, 0.33479684])

In [13]:
np.random.randn(10)

array([ 0.24905632,  0.49090611,  1.2843905 ,  0.68389466,  0.76369199,
        1.27666646, -0.11851084, -0.25853033,  0.827268  , -0.40618272])

In [14]:
# (start, end, numbers_of_elements)
np.random.randint(0,10,10)

array([6, 1, 1, 1, 6, 2, 6, 3, 3, 2])

# Array Attributes

In NumPy, **array attributes** are built-in properties of the `ndarray` object that provide critical details about its structure, data type, and memory layout. You can access these properties directly using dot notation (e.g., `array.shape`) without calling
them like functions.


---

| Attribute | What it Returns | Example Output (for a 2×3 array) |
|---|---|---|
| `.shape` | A tuple showing the size of the array in each dimension (rows, columns). | `(2, 3)` |
| `.ndim` | The number of array dimensions (axes). | `2` |
| `.dtype` | The data type of the elements stored in the array. | `dtype('int64')` |
| `.size` | The total number of elements across all dimensions. | `6` |
| `.itemsize` | The size of a single array element in bytes. | `8` (for a 64-bit integer) |
| `.nbytes` | The total memory consumed by all elements (`size × itemsize`). | `48` (6 elements × 8 bytes) |

In [19]:
arr = np.array([[1,2,3,4],[4,5,6.9,7],[5,6,7,8]])
arr

array([[1. , 2. , 3. , 4. ],
       [4. , 5. , 6.9, 7. ],
       [5. , 6. , 7. , 8. ]])

In [20]:
arr.shape

(3, 4)

In [21]:
arr.size

12

In [22]:
arr.dtype

dtype('float64')

In [25]:
arr.min()

np.float64(1.0)

In [26]:
arr.max()

np.float64(8.0)

In [27]:
arr.sum()

np.float64(58.9)

In [28]:
# np.sum (array, axis)
#  1----> row wise
#  0 ----> column wise
np.sum(arr,axis = 0)

array([10. , 13. , 16.9, 19. ])

In [29]:
arr.std()

np.float64(2.0918326627359294)

In [30]:
# index of maximum element
arr.argmax()

np.int64(11)

In [32]:
# index of minimum element
arr.argmin()

np.int64(0)

# Reshaping & Resizing

In [33]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
# Reshaping the above array
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [37]:
arr = np.array([1, 2, 3, 4])

# np.resize() returns a new array and repeats data if the new size is larger
larger_arr = np.resize(arr, (2, 3))
print(larger_arr)
# Output:
# [[1 2 3]
#  [4 1 2]]  <-- Repeats elements from the beginning to fill the space

# array.resize() updates the array in-place and pads with zeros if larger
arr.resize((2, 3), refcheck=False)
print(arr)
# Output:
# [[1 2 3]
#  [4 0 0]]  <-- Pads the extra space with zeros

[[1 2 3]
 [4 1 2]]
[[1 2 3]
 [4 0 0]]


# Indexing and Slicing of Vectors

**Indexing**

NumPy Arrays use **0-based indexing**. You can use positive integers (countinf from the front ) or negative integers ( counting from the back )

In [43]:
#  1D Array
arr = np.array([10,20,30,40])
print(f"element is---> {arr[0]}") # Output: 10  (First element)
print(f"element is----> {arr[-1]}")  # Output: 40  (Last element)

element is---> 10
element is----> 40


In [49]:
#  2D Array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [7,8,9,0]])
print(arr[1,2]) # Output: 7  (Row index 1, Column index 2)

7


**Slicing**

Slicing allows you to extract a range of element using the syntax `[start : stop : step ]`

*   `start`: The index where the slice begins (included, default to 0 ).
*   `stop`: The index where the slice end ( excluded, default to array length ).   
*   `step`: The interval b/w elements ( default to 1 )





In [55]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[1:5]) # Output: [1, 2, 3, 4] (Indices 1 to 4)
print(arr[:4]) # Output: [0, 1, 2, 3] (From start up to index 4)
print(arr[5:])     # Output: [5, 6, 7, 8, 9] (From index 5 to the end)
print(arr[1:8:2])  # Output: [1, 3, 5, 7] (Every 2nd element from 1 to 7)
print(arr[::-1])   # Output: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] (Reverses the array)

[1 2 3 4]
[0 1 2 3]
[5 6 7 8 9]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [58]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [7,8,9,0]])
'''
arr[row_slice, column_slice] extracts
a specific subsection(sub-array)of 2D array.
'''
print(arr[0:2, 1:3])


[[2 3]
 [6 7]]


# Boolean Indexing

Boolean Indexing in NumPy allows you to filter, select or modify elements in an array based
on a **specific condition**. When you pass a condition inside the square brackets, NumPy allows you to filter, select, or modify elements in an array based on a specific condition. When you pass a condition inside the square brackets, NumPy creates a temporary "boolean mask" (an array of `True` and `False` values) and returns only the elements where the mask is `True`.

**1D Array**

In [59]:
arr = np.array([15,20,25,30,35,40,45,50,55])
print(arr[arr % 2 == 0])

[20 30 40 50]


In [60]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False])

In [61]:
arr[bool_index]

array([20, 30, 40, 50])

**Combining Multiple Condition**

⚠️ Important: You must wrap each individual condition in parentheses `()` due to operator precedence rules in Python

In [63]:
bool_index = (arr % 2 == 0) & (arr > 30)
arr[bool_index]

array([40, 50])

**2D Array Indexing**

In [64]:
matrix = np.array([[1, 6, 3],
                   [8, 2, 9]])

# Find all even numbers in the matrix
evens = matrix[matrix % 2 == 0]
print(evens)
# Output: [6, 8, 2]


[6 8 2]


In [65]:
# Select rows where the first column's value is greater than 5
# matrix[:, 0] > 5 gives [False, True]
filtered_rows = matrix[matrix[:, 0] > 5]
print(filtered_rows)
# Output: [[8, 2, 9]]


[[8 2 9]]
